//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercicio3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluguer
    {
        public Aluguer()
        {
            this.LogEvento = new HashSet<LogEvento>();
        }
    
        public int @ref { get; set; }
        public System.DateTime data_reserva { get; set; }
        public int local_recolha { get; set; }
        public System.DateTime datahora_recolha { get; set; }
        public int local_entrega { get; set; }
        public System.DateTime datahora_entrega { get; set; }
        public decimal tarifa_base_a_aplicar { get; set; }
        public int nr_dias { get; set; }
        public Nullable<decimal> valor_total { get; set; }
        public string estado { get; set; }
        public int cliente { get; set; }
        public string rentacar { get; set; }
        public string grupo { get; set; }
        public string veiculo { get; set; }
        public Nullable<float> km_inicio { get; set; }
        public Nullable<float> km_fim { get; set; }
    
        public virtual Precario Precario { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        public virtual Local Local { get; set; }
        public virtual Local Local1 { get; set; }
        public virtual Veiculo Veiculo1 { get; set; }
        public virtual ICollection<LogEvento> LogEvento { get; set; }
    }
}
