//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercicio3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Aluguer = new HashSet<Aluguer>();
        }
    
        public int nr_cliente { get; set; }
        public string nome { get; set; }
        public int telefone { get; set; }
        public int nif { get; set; }
        public int pontos { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<Aluguer> Aluguer { get; set; }
    }
}
