//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercicio3
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEvento
    {
        public int @ref { get; set; }
        public int aluguer { get; set; }
        public System.DateTime data { get; set; }
        public string mensagem { get; set; }
        public string tipo { get; set; }
    
        public virtual Aluguer Aluguer1 { get; set; }
    }
}
