//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercicio3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SI2_1314i_TPEntities : DbContext
    {
        public SI2_1314i_TPEntities()
            : base("name=SI2_1314i_TPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aluguer> Aluguer { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Empresa_Aluguer> Empresa_Aluguer { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<Local> Local { get; set; }
        public virtual DbSet<LogEvento> LogEvento { get; set; }
        public virtual DbSet<Precario> Precario { get; set; }
        public virtual DbSet<Veiculo> Veiculo { get; set; }
    }
}
