//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercicio3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precario
    {
        public Precario()
        {
            this.Aluguer = new HashSet<Aluguer>();
        }
    
        public string rentacar { get; set; }
        public string grupo { get; set; }
        public decimal tarifa_base { get; set; }
        public int quota_freesale { get; set; }
    
        public virtual ICollection<Aluguer> Aluguer { get; set; }
        public virtual Empresa_Aluguer Empresa_Aluguer { get; set; }
        public virtual Grupo Grupo1 { get; set; }
    }
}
